from __future__ import annotations
from typing import Protocol, Iterable, Optional, Any
from app.models.qdrant.qdrant_models import ReportRecord, UpsertBatchResult, SearchHit

class ReportsIndex(Protocol):
    def upsert_reports_batch(self, user_id: str, reports: Iterable[ReportRecord]) -> UpsertBatchResult: ...
    def search(self, user_id: str, query: str, *, limit: int = 5, include_text: bool = False) -> list[SearchHit]: ...
    def search_by_tags(self, user_id: str, tags: list[str], *, limit: int = 10, include_text: bool = False) -> list[SearchHit]: ...
    def search_by_date_range(self, user_id: str, start_date: str, end_date: str, *, limit: int = 10, include_text: bool = False) -> list[SearchHit]: ...
    def get_by_id(self, user_id: str, report_id: str, *, include_text: bool = True) -> Optional[SearchHit]: ...
    def get_user_stats(self, user_id: str) -> dict[str, Any]: ...
