from __future__ import annotations
from typing import Protocol, Optional, Iterable

from app.models.qdrant.qdrant_models import TemplateRecord, TemplateHit, UpsertBatchResult

class TemplatesIndex(Protocol):
    def upsert_template(self, user_id: str, template: TemplateRecord) -> UpsertBatchResult: ...
    def search_templates(self, user_id: str, query: str, *, limit: int = 5, include_text: bool = True) -> list[TemplateHit]: ...
    def list_user_templates(self, user_id: str) -> list[TemplateHit]: ...
    def get_template_by_id(self, user_id: str, template_id: str,) -> Optional[TemplateHit]: ...